name: CI Pipeline for SPM Project
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  unit_testing:
     runs-on: ubuntu-latest

     steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python version 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run unit tests
        run: |
          cd spm_project/src/Flask
          python -m pytest
          
      


    
